export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      leads: { Row: { id: string; created_at: string; name: string; email: string; phone: string | null; budget: string | null; timeline: string | null; buyer_type: string | null; neighborhoods: string[] | null; message: string | null; source_page: string | null }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      properties: { Row: { id: string; created_at: string; slug: string; name: string; neighborhood: string; price_usd: number | null; bedrooms: number | null; adr_low: number | null; adr_high: number | null; annual_gross_low: number | null; annual_gross_high: number | null; status: string }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      market_reports: { Row: { id: string; created_at: string; title: string; period: string; summary: string | null; pdf_path: string | null; published: boolean }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      benchmark_data: { Row: { id: string; created_at: string; period: string; source_name: string; source_type: string; payload: Json; notes: string | null }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      articles: { Row: { id: string; created_at: string; slug: string; title: string; category: string; excerpt: string | null; body: string | null; published: boolean }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      site_content: { Row: { id:string; key:string; value:Json; status:string; created_at:string; updated_at:string; updated_by:string | null }; Insert: Partial<this['Row']> & { key:string; value:Json }; Update: Partial<this['Insert']> };

      roi_submissions: { Row: { id: string; created_at: string; lead_id: string | null; input_payload: Json; output_payload: Json | null; version_tag: string }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      media_assets: { Row: { id: string; created_at: string; storage_bucket: string; storage_path: string; mime_type: string | null; module: string | null; alt_text: string | null; uploaded_by: string | null }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      import_jobs: { Row: { id: string; created_at: string; source_system: string; source_type: string; status: string; input_uri: string | null; output_summary: Json | null; error_log: string | null; started_at: string | null; finished_at: string | null }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      user_roles: { Row: { id: string; user_id: string; role: string; permissions: Json; assigned_at: string }; Insert: Omit<this['Row'], 'id'|'assigned_at'> & { id?: string; assigned_at?: string }; Update: Partial<this['Insert']> };
      audit_logs: { Row: { id: string; created_at: string; actor_user_id: string | null; module: string; action: string; entity_type: string | null; entity_id: string | null; before_state: Json | null; after_state: Json | null; metadata: Json | null }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      investment_assumption_versions: { Row: { id: string; created_at: string; property_id: string | null; version_no: number; assumptions: Json; created_by: string; is_active: boolean }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      event_tracking: { Row: { id: string; created_at: string; event_name: string; module: string; actor_id: string | null; session_id: string | null; payload: Json | null }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };
      gated_access_grants: { Row: { id: string; created_at: string; lead_id: string | null; resource_type: string; resource_id: string; access_status: string; granted_at: string | null; expires_at: string | null }; Insert: Omit<this['Row'], 'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<this['Insert']> };

      market_data_imports: { Row: { id:string; source_type:string; period:string; imported_file_name:string | null; import_batch_id:string; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string; import_batch_id:string }; Update: Partial<this['Insert']> };
      market_monthly_performance: { Row: { id:string; source_type:string; period:string; month:number; year:number; lrm_occupancy:number | null; market_occupancy:number | null; lrm_adr:number | null; market_adr:number | null; lrm_revpar:number | null; market_revpar:number | null; imported_file_name:string | null; import_batch_id:string | null; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string; month:number; year:number }; Update: Partial<this['Insert']> };
      market_bedroom_performance: { Row: { id:string; source_type:string; period:string; bedroom_count:string; lrm_adr:number | null; market_adr:number | null; lrm_occupancy:number | null; market_occupancy:number | null; lrm_revpar:number | null; market_revpar:number | null; imported_file_name:string | null; import_batch_id:string | null; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string; bedroom_count:string }; Update: Partial<this['Insert']> };
      market_neighborhood_performance: { Row: { id:string; source_type:string; period:string; month:number | null; year:number | null; neighborhood:string; lrm_adr:number | null; market_adr:number | null; lrm_occupancy:number | null; market_occupancy:number | null; lrm_revenue:number | null; market_revenue_estimate:number | null; imported_file_name:string | null; import_batch_id:string | null; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string; neighborhood:string }; Update: Partial<this['Insert']> };
      market_channel_mix: { Row: { id:string; source_type:string; period:string; month:number | null; year:number | null; channel_name:string; channel_share:number; imported_file_name:string | null; import_batch_id:string | null; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string; channel_name:string; channel_share:number }; Update: Partial<this['Insert']> };
      market_seasonality: { Row: { id:string; source_type:string; period:string; month:number; year:number; demand_index:number; imported_file_name:string | null; import_batch_id:string | null; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string; month:number; year:number; demand_index:number }; Update: Partial<this['Insert']> };
      airdna_benchmark_data: { Row: { id:string; source_type:string; period:string; month:number | null; year:number | null; neighborhood:string | null; bedroom_count:string | null; occupancy:number | null; adr:number | null; revpar:number | null; supply:number | null; demand:number | null; imported_file_name:string | null; import_batch_id:string | null; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string }; Update: Partial<this['Insert']> };
      data_validation_errors: { Row: { id:string; source_type:string; period:string; row_number:number | null; table_name:string; import_batch_id:string | null; error_code:string; error_message:string; raw_row:Json | null; imported_file_name:string | null; status:string; created_at:string; updated_at:string; created_by:string | null; notes:string | null }; Insert: Partial<this['Row']> & { source_type:string; period:string; table_name:string; error_code:string; error_message:string }; Update: Partial<this['Insert']> };


    };
  };
}
